config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get "/campaigns/dashboard", to: "campaigns#dashboard", as: "dashboard"

    resources :campaigns do
      resources :comments
      resources :donations
    end

  get "/:category/campaigns" => "campaigns#category", as: "category"

  get "/join" => "users#new", as: "signup"
  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  get "/profile" => "sessions#show", as: "profile"
  get "/profile/edit" => "users#edit", as: "edit_profile"
  get "/profile/password" => "users#password", as: "password_profile"

  get '/contact' => 'contact_us/contacts#new', as: "contact"
  get '/contact/thanks' => 'contact_us/contacts#thanks'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  scope :active, ->{where(["finalizado_en >= ?", Date.today])}

  def self.categories
    ["Medical", "Sports", "Events", "Animals", "Education"]
  end

  has_many :comments
  has_many :donations

  belongs_to :user

  validates :titulo, presence: true
  validates :resena, presence: true, length: {maximum: 140}
  validates :meta, presence: true, numericality: {greater_than: 0}
  validates :category, presence: true
  validate :date_is_before_six_months

  def date_is_before_six_months
    if self.finalizado_en.present? && (self.finalizado_en > (Date.today + 6.months))
      errors.add(:finalizado_en, 'No puede durar mas de 6 meses')
    end
  end

  before_create :default_image
  before_update :default_image

  before_create :default_date
  before_update :default_date

  protected

  def default_image
    if image == ""
      self.image='https://www.hsjaa.com/images/joomlart/demo/default.jpg'
    end
  end

  def default_date
    if finalizado_en == nil
      self.finalizado_en = Date.today + 6.months
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :campaign
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :campaign

  validates :monto, presence: true, numericality: {greater_than: 0}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :campaigns

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   helper_method :current_user, :authenticate
  before_action :authenticate


  def login(user)
  	session[:user_id] = user.id
  	redirect_to dashboard_path
  end

  def logout
  	reset_session
  	redirect_to root_path
  end

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def authenticate_logeado
    if current_user
      redirect_to dashboard_path
    end
  end

  def authenticate
    unless current_user
      redirect_to login_path
    end
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  skip_before_action :authenticate, only: [:index, :show, :category]

  def index
    @campaigns = Campaign.active.order(:created_at)
  end

  def show
    @campaign = Campaign.find(params[:id])
    @user = User.find_by(id: @campaign.user_id)
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id
    @campaign.cant_like = 0

    if @campaign.save
      UserNotifierMailer.campaign_create(current_user, @campaign).deliver
      redirect_to dashboard_path, notice: "Se agrego exitosamente."
    else
      render :new
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])

    if @campaign.update_attributes(campaign_params)
      if current_user.receive_email
        UserNotifierMailer.campaign_edit(current_user, @campaign).deliver
      end
      redirect_to campaign_path(@campaign),  notice: "Se edito con exito."
    else
      render :edit
    end
  end




  def category
    @campaigns = Campaign.where(["category like ?", params[:category]])
    @category = params[:category].to_s
  end

  def dashboard
    @campaigns = Campaign.where(["user_id = ?", current_user.id])
  end

  protected

  def campaign_params
    params.require(:campaign).permit!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def new
  @campaign = Campaign.find(params[:campaign_id])
  @comment = @campaign.comments.build
  end

def create
  @campaign = Campaign.find(params[:campaign_id])
  @comment = @campaign.comments.build(comments_params)
  @user = User.find_by(id: @campaign.user_id)

  if @comment.save
    if @user.receive_email
      UserNotifierMailer.new_comment(@user, @comment, @campaign).deliver
    end
    redirect_to @campaign,  notice: "Se agrego con exito"
  else
    render :new
  end
end

def destroy
  @campaign = Campaign.find(params[:campaign_id])
  @comment = @campaign.comments.find(params[:id])
  @comment.destroy
  redirect_to @campaign,  notice: "Se borro con exito"
end

protected

  def comments_params
      params.require(:comment).permit!
  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def new
  @campaign = Campaign.find(params[:campaign_id])
  @donation = @campaign.donations.build
  end

def create
  @campaign = Campaign.find(params[:campaign_id])
  @donation = @campaign.donations.build(donations_params)
  @user = User.find_by(id: @campaign.user_id)



  if @donation.save
    if @user.receive_email
      UserNotifierMailer.new_donation(@user, @donation, @campaign).deliver
    end
    redirect_to @campaign,  notice: "Se agrego con exito"
  else
    render :new
  end
end

def destroy
  @campaign = Campaign.find(params[:campaign_id])
  @donation = @campaign.donations.find(params[:id])
  @donation.destroy
  redirect_to @campaign,  notice: "Se borro con exito"
end

protected

  def donations_params
      params.require(:donation).permit!
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate

  def index
    @campaigns = Campaign.where(["finalizado_en > ?", Date.today]).order(:cant_like).limit( 5 )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def new
    if current_user
      redirect_to root_path
    end
  end

  def create
    authenticate_logeado

    email = params[:session][:email]
    password = params[:session][:password]

    @user = User.find_by(email: email)

    if @user && @user.authenticate(password)
      login(@user)
    else
      redirect_to dashboard_path, flash: { error: "Email o Password incorrecto"}
    end
  end

  def show
    @current_user = current_user
  end

  def destroy
    if current_user
      logout
    else
      redirect_to login_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def new
    authenticate_logeado
    @user = User.new
  end

def create
  @user = User.new(user_params)
  @user.receive_email=true

  if @user.save
    UserNotifierMailer.signup_email(@user).deliver
    login(@user)
    redirect_to root_path, notice: "Se agrego exitosamente."
  else
    render :new
  end
end

def edit
  @user = current_user
end

def password
  @user = current_user
end

def update
  @user = current_user

  if @user.update_attributes(user_params)
    UserNotifierMailer.password_edit(@user).deliver
    redirect_to profile_path
  else
    render :edit
  end
end

protected

def user_params
  params.require(:user).permit!
end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def porciento_completado(campaign)
    return 0 unless campaign.donations.any?
    campaign.donations.sum(:monto).to_f/campaign.meta
  end

  def cant_recuadada(donations)
    return 0 unless donations.any?
    donations.sum(:monto)
  end

  def format_date(fecha)
  return nil unless fecha
  fecha.strftime("%B %e, %Y")
end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campaigns/_campaign_comments.html.erb
<% if campaign.comments.any? %>
	<div>
		<h2>Comments: </h2>
		<table border="2">
			<thead>
				<th>ID</th>
				<th>Nombre</th>
			</thead>
			<tbody>
				<%= render campaign.comments.order("created_at DESC") %>
			</tbody>
		</table>
	</div>
<% else %>
	<p><em>No hay categories.</em></p>
<% end %>

app/views/campaigns/_campaign_donations.html.erb
<% if donations.any? %>
	<div>
		<h2>Donations: </h2>
		<table class="table table-striped">
			<thead>
				<th>Autor</th>
				<th>Monto Hecho</th>
		        <th>Mensaje</th>
		        <th>Fecha Creado</th>
			</thead>
			<tbody>
				<%= render donations %>
			</tbody>
		</table>
	</div>
<% else %>
	<p><em>No donations.</em></p>
<% end %>
<%= link_to "New Donation", new_campaign_donation_path(@campaign.id), class:"btn btn-default btn-lg" %> 

app/views/campaigns/category.html.erb
<% if flash[:notice] %>
	<div>
		<%= flash[:notice] %>
	</div>
<% end %>

<div class="jumbotron">
	<div class="container">
		<h1>
			<% if @category == "Medical" %>
				<span class="icon-heart"></span> Medical
			<% end %>
			<% if @category == "Sports" %>
				<span class="icon-futbol-o"></span> Sports
			<% end %>
			<% if @category == "Events" %>
				<span class="icon-calendar-o"></span> Events
			<% end %>
			<% if @category == "Animals" %>
				<span class="icon-paw"></span> Animals
			<% end %>
			<% if @category == "Education" %>
				<span class="icon-book"></span> Education
			<% end %>
		</h1>

		<% if @category == "Medical" %>
			<p>
				
				Raise money for medical bills and expenses. Fundraising for medical bills and related medical expenses.
				We have raised over $3 Billion for people in need.
				#1 for Medical, Illness &amp; Healing fundraising
				Set up a Powerful Fundraiser in less than 30 Seconds.
				Get real results fast!
			</p>
		<% end %>
		<% if @category == "Sports" %>
			<p>
				
				Raise money for sports teams and clubs.
				We have raised over $3 Billion for people in need.
				#1 for Sports, Teams &amp; Clubs fundraising
				Set up a Powerful Fundraiser in less than 30 Seconds.
				Get real results fast!
			</p>
		<% end %>
		<% if @category == "Events" %>
			<p>
				
				Raise money for weddings, parties, showers, &amp; more.
				We have raised over $3 Billion for people in need.
				#1 for Celebrations &amp; Events fundraising
				Set up a Powerful Fundraiser in less than 30 Seconds.
				Get real results fast!
			</p>
		<% end %>
		<% if @category == "Animals" %>
			<p>
				
				Raise money for your favorite pets
				We have raised over $3 Billion for people in need.
				#1 for Animals &amp; Pets fundraising
				Set up a Powerful Fundraiser in less than 30 Seconds.
				Get real results fast!
			</p>
		<% end %>
		<% if @category == "Education" %>
			<p>
				
				Raise money for education supplies and expenses.
				We have raised over $3 Billion for people in need.
				#1 for Education &amp; Learning fundraising
				Set up a Powerful Fundraiser in less than 30 Seconds.
				Get real results fast!
			</p>
		<% end %>
	</div>
</div>

<div class="categories-desc">
    <div class="row">
        
		<%- @campaigns.each do |f| %>
	        <div class="col-sm-6 col-md-4">
	            <div class="thumbnail">
	            	<%= image_tag f.image, alt: "Medical" %>
	                <div class="caption">
	                    <div class="progress">
	                        <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%=porciento_completado(f) * 100 %>%">
      							<%= number_to_percentage(porciento_completado(f) * 100, precision: 0)  %>
	                        </div>
	                    </div>
	                    <h3><%= link_to f.titulo, campaign_path(f) %></h3>
	                    <p><%= f.resena %></p>
	                    <div class="overlay"></div>
                        <%= link_to campaign_path(f), class: "btn btn-link" do %>
                            <span class="icon-plus"></span> Read More
                        <% end %>
	                    
	                </div>
	            </div>
	        </div>
		<%- end %>
	</div>
</div>

app/views/campaigns/dashboard.html.erb
<h1 >My Dashboard</h1>

<% if flash[:notice] %>
	<div>
		<%= flash[:notice] %>
	</div>
<% end %>

<div class="categories-desc">
    <div class="row">
        
		<%- @campaigns.each do |f| %>
	        <div class="col-sm-6 col-md-4">
	            <div class="thumbnail">
	            	<%= image_tag f.image, alt: "Medical" %>
	                <div class="caption">
	                    <div class="progress">
	                        <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%=porciento_completado(f) * 100 %>%">
      							<%= number_to_percentage(porciento_completado(f) * 100, precision: 0)  %>
	                        </div>
	                    </div>
	                    <h3><%= link_to f.titulo, campaign_path(f) %></h3>
	                    <p><%= f.resena %></p>
	                    <div class="overlay"></div>
                        <%= link_to campaign_path(f), class: "btn btn-link" do %>
                            <span class="icon-plus"></span> Read More
                        <% end %>
	                    
	                </div>
	            </div>
	        </div>
		<%- end %>
	</div>
</div>

app/views/campaigns/edit.html.erb
<h1>Edit Campaign</h1>
<p> <em> Ingrese los datos necesarios: </em> </p>

<% if @campaign.errors.any? %>
  <div>
    Por favor corrija los siguientes problemas:
    <ul>
      <% @campaign.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>


<div>
  <%= form_for @campaign do |f| %>
    <p>
      <%= f.label :titulo, "Titulo", class: "input-group"%>
      <%= f.text_field :titulo, class: "form-control" %>
    </p>

    <p>
      <%= f.label :resena, "Resena", class: "input-group"  %>
      <%= f.text_field :resena, class: "form-control" %>
    </p>

    <p>
      <%= f.label :description , class: "input-group"%>
      <%= f.text_area :description, class: "form-control"%>
    </p>

    <p>
      <%= f.label :category , class: "input-group"%>
      <%= f.select :category, Campaign.categories, class: "form-control"%>
    </p>

    <p>
      <%= f.label :image, "Imagen", class: "input-group" %>
      <%= f.text_field :image, class: "form-control" %>
    </p>

    <p>
      <%= f.label :finalizado_en, "Finaliza en", class: "input-group" %>
      <%= f.date_field :finalizado_en, class: "form-control" %>
    </p>

    <p>
      <%= f.submit "Update", class:"btn btn-default btn-lg" %>
      <%= link_to "Cancelar", campaigns_path, class:"btn btn-default btn-lg" %>
      <% unless @campaign.donations.any? %>
        <%= link_to "Borrar", @campaign, method: :delete, data: {confirm: "Are you really sure?"}, class:"btn btn-default btn-lg" %>
      <% end %>
    </p>

  <% end %>

</div>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>
<p> <em> Ingrese los datos necesarios: </em> </p>

<% if @campaign.errors.any? %>
  <div>
    Por favor corrija los siguientes problemas:
    <ul>
      <% @campaign.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div style="width: 500px">
  <%= form_for @campaign do |f| %>
    <p>
      <%= f.label :titulo, "Titulo", class: "input-group"%>
      <%= f.text_field :titulo, class: "form-control" %>
    </p>

    <p>
      <%= f.label :resena, "Resena", class: "input-group"  %>
      <%= f.text_field :resena, class: "form-control" %>
    </p>

    <p>
      <%= f.label :description , class: "input-group"%>
      <%= f.text_area :description, class: "form-control"%>
    </p>

    <p>
      <%= f.label :category , class: "input-group"%>
      <%= f.select :category, Campaign.categories, class: "dropdown"%>
    </p>

    <p>
      <%= f.label :meta, class: "input-group"%>
      <%= f.number_field :meta, class: "form-control"%>
    </p>

    <p>
      <%= f.label :image, "Imagen", class: "input-group" %>
      <%= f.text_field :image, class: "form-control" %>
    </p>

    <p>
      <%= f.label :finalizado_en, "Finaliza en", class: "input-group" %>
      <%= f.date_field :finalizado_en, class: "form-control" %>
    </p>

    <p>
      <%= f.submit "Crear", class:"btn btn-default btn-lg" %>
      <%= link_to "Cancelar", campaigns_path, class:"btn btn-default btn-lg" %>
    </p>

  <% end %>
</div>

app/views/campaigns/show.html.erb

<% if flash[:notice] %>
  <div style="background: yellow">
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="row">
  <div class="col-md-6 jumbotron">
    <h1><%=@campaign.titulo %></h1>
    <%= image_tag @campaign.image, style: "heigth: 400px; width: 400px; padding-bottom: 10px" %>


    <div class="progress" style="width: 400px;">
      <div class="progress-bar" role="progressbar" aria-valuenow= "<%=porciento_completado(@campaign) * 100 %>"
      aria-valuemin="0" aria-valuemax="100" style="width: <%=porciento_completado(@campaign) * 100 %>%">
      <%= number_to_percentage(porciento_completado(@campaign) * 100, precision: 0)  %> Completado
      </div>
    </div>
    <ul class="list-group">
      <li class="list-group-item"><%=@user.name %></li>
      <li class="list-group-item"><%=@user.ciudad %>, <%=@user.pais %></li>
      <li class="list-group-item"><%= mail_to @user.email, "Enviar correo" %></li>
    </ul>
    <br>
    <ul class="list-group">
      <li class="list-group-item">
        Description:
        <light><%= @campaign.description %></light>
      </li>
      <li class="list-group-item">
        Meta:
        <light><%= @campaign.meta %></light>
      </li>
      <li class="list-group-item">
        Category:
        <light><%= link_to @campaign.category, category_path(@campaign.category) %></light>
      </li>
      <li class="list-group-item">
        Cantidad de Likes:
        <light><%= @campaign.cant_like %></light>
      </li>
      <li class="list-group-item">
        Fecha culminacion:
        <light><%= format_date(@campaign.finalizado_en) %></light>
      </li>
      <li class="list-group-item">
        Fecha creacion:
        <light><%= format_date(@campaign.created_at)  %></light>
      </li>
    </ul>
    <% if current_user %>
      <% if current_user.id == @campaign.user_id %>
        <p style="display: inline-block"> <%= link_to "Edit", edit_campaign_path, class:"btn btn-default btn-lg" %> </p>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-6 jumbotron">
    <h1>Comentarios</h1>
    <% if @campaign.comments.any? %>

      <%- @campaign.comments.each do |f| %>
      <ul class="list-group">
        <li class="list-group-item">
          <span class="badge"><%= format_date(f.created_at)%></span>
          <b><%= f.autor %></b>
          <br>
          &emsp; <%= f.mensaje %>
          <% if current_user %>
              <% if current_user == User.find_by(name: f.autor) %>
                 <%= link_to "X", campaign_comment_path(f.campaign, f), method: :delete, data: {confirm: "Estas Seguro?"}, class:"btn btn-default btn-sm pull-right" %>
              <% end %>
          <% end %>
        </li>
      </ul>
      <%- end %>
      <% else %>
        <p><em>No hay comentarios.</em></p>
      <% end %>
      <%= link_to "New Comment", new_campaign_comment_path(@campaign.id), class:"btn btn-default btn-lg" %> 
  </div>
</div>
<div class="row">
  <div class="col-md-12 jumbotron">
    <%= render partial: "campaign_donations", locals: {donations: @campaign.donations.order("created_at DESC")} %>
  </div>
</div>























app/views/comments/_comment.html.erb
<tr>
	<td><%= comment.autor %> </td>
	<td><%= comment.mensaje %> </td>
	<td><%= comment.created_at %> </td>
</tr>

app/views/comments/new.html.erb
<h1>Nuevo Comment</h1>

<div>
	<%= render partial: "shared/errors", locals: { obj: @comment } %>

	<%= form_for [@campaign, @comment] do |f| %>
		<% if current_user %>
		<p>
			<%= f.hidden_field :autor, value: User.find(current_user.id).name %>
		</p>
		<% else %>
		<p>
			<%= f.label :autor, "Autor" %>
			<%= f.text_field :autor %>
		</p>
		<% end %>

		<p>
      <%= f.label :mensaje, "Descripcion" %>
      <%= f.text_area :mensaje %>
    </p>
    <p>
		<p>
			<%= f.submit "Agregar comment" , class:"btn btn-default btn-lg"%>
			<%= link_to "Cancelar", @campaign , class:"btn btn-default btn-lg"%>
		</p>
	<% end %>
</div>

app/views/home/index.html.erb
<div class="home">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="<%= image_url('go-fund-blank-light.jpeg') %>" alt="carrusel!!!">
                <div class="carousel-caption">
                    Go found <span class="bold">anything</span>|
                </div>
            </div>
            <div class="item">
                <img src="<%= image_url('go-fund-family-light.jpeg') %>" alt="carrusel!!!">
                <div class="carousel-caption">
                    Go found <span class="bold">a family</span>|
                </div>
            </div>
            <div class="item">
                <img src="<%= image_url('go-fund-pet-light.jpg') %>" alt="carrusel!!!">
                <div class="carousel-caption">
                    Go found <span class="bold">a pet</span>|
                </div>
            </div>
            <div class="item">
                <img src="<%= image_url('go-fund-project-light.jpeg') %>" alt="carrusel!!!">
                <div class="carousel-caption">
                    Go found <span class="bold">a project</span>|
                </div>
            </div>
            <div class="item">
                <img src="<%= image_url('go-fund-classroom-light.jpeg') %>" alt="carrusel!!!">
                <div class="carousel-caption">
                    Go found <span class="bold">a classroom</span>|
                </div>
            </div>
            <div class="form">
                <%= link_to "Start a Campaign", new_campaign_path, class: "btn btn-primary btn-lg" %>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row categories">
                <div class="item col-md-2 col-md-offset-1">
                    <%= link_to category_path("Medical"), class: "col-md-12" do %>
                        <span class="icon-heart"></span>
                    <% end %>
                    <span class="title">
                        Medical
                    </span>
                </div>
                <div class="item col-md-2">
                    <%= link_to category_path("Sports"), class: "col-md-12" do %>
                        <span class="icon-futbol-o"></span>
                    <% end %>
                    <span class="title">
                        Sports
                    </span>
                </div>
                <div class="item col-md-2">
                    <%= link_to category_path("Events"), class: "col-md-12" do %>
                        <span class="icon-calendar-o"></span>
                    <% end %>
                    <span class="title">
                        Events
                    </span>
                </div>
                <div class="item col-md-2">
                    <%= link_to category_path("Animals"), class: "col-md-12" do %>
                        <span class="icon-paw"></span>
                    <% end %>
                    <span class="title">
                        Animals
                    </span>
                </div>
                <div class="item col-md-2">
                    <%= link_to category_path("Education"), class: "col-md-12" do %>
                        <span class="icon-book"></span>
                    <% end %>
                    <span class="title">
                        Education
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="categories-desc">
        <div class="row">
            
            <%- @campaigns.each do |f| %>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <%= image_tag f.image, alt: "Medical" %>
                    <div class="caption">
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%=porciento_completado(f) * 100 %>%">
                                <%= number_to_percentage(porciento_completado(f) * 100, precision: 0)  %>
                            </div>
                        </div>
                        <h3>
                        <%= link_to campaign_path(f) do %>
                            <% if f.category == "Medical" %>
                                <span class="icon-heart"></span> f.titulo
                            <% end %>
                            <% if f.category == "Sports" %>
                                <span class="icon-futbol-o"></span> f.titulo
                            <% end %>
                            <% if f.category == "Events" %>
                                <span class="icon-calendar-o"></span> f.titulo
                            <% end %>
                            <% if f.category == "Animals" %>
                                <span class="icon-paw"></span> f.titulo
                            <% end %>
                            <% if f.category == "Education" %>
                                <span class="icon-book"></span> f.titulo
                            <% end %>
                        <% end %>
                                
                        </h3>
                        <p><%= f.resena %></p>
                        <div class="overlay"></div>
                        <%= link_to campaign_path(f), class: "btn btn-link" do %>
                            <span class="icon-plus"></span> Read More
                        <% end %>
                        
                    </div>
                </div>
            </div>
        <%- end %>
        </div>
    </div>
        
</div>


app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<img alt="Brand" src="<%= image_url('logo.png') %>">
			</a>
		</div>
		<ul class="nav navbar-nav navbar-right">
			<li><%= link_to "Start a Fundraiser", new_campaign_path %></li>
			<li class="dropdown">
				<button type="button" class="tcon tcon-menu--xcross dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<span class="tcon-menu__lines" aria-hidden="true"></span>
					<span class="tcon-visuallyhidden">toggle menu</span>
				</button>
				
				<ul class="dropdown-menu">
                    <li>
                        <%= link_to "Home", root_path%>
                    </li>
                    <li>
                        <%= link_to "Contact Us", contact_path %>
                    </li>
                    <li>
                        <%= link_to "Campaigns", campaigns_path %>
                    </li>
                    <% if current_user %>
	                    <li>
	                      <%= link_to "Start a Campaign", new_campaign_path %>
	                    </li>

	                    <li>
	                      <%= link_to "My Dashboard", dashboard_path %>
	                    </li>

	                    <li>
	                      <%= link_to "Profile", profile_path %>
	                    </li>

	                    <li>
	                      <%= link_to "Log Out", logout_path  %>
	                    </li>
                    <% else%>
	                    <li>
	                      <%= link_to "Log In", login_path %>
	                    </li>
	                    <li>
	                      <%= link_to "Sign Up", signup_path %>
	                    </li>
                    <%end%>
                </ul>
			</li>
		</ul>
	</div>
</nav>